# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import database_pb2 as database__pb2


class databaseStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.queryDatabase = channel.unary_unary(
        '/database/queryDatabase',
        request_serializer=database__pb2.databaseRequest.SerializeToString,
        response_deserializer=database__pb2.databaseResponse.FromString,
        )


class databaseServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def queryDatabase(self, request, context):
    """Query the database
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_databaseServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'queryDatabase': grpc.unary_unary_rpc_method_handler(
          servicer.queryDatabase,
          request_deserializer=database__pb2.databaseRequest.FromString,
          response_serializer=database__pb2.databaseResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'database', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
