# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: database.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='database.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64\x61tabase.proto\" \n\x0f\x64\x61tabaseRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\'\n\x10\x64\x61tabaseResponse\x12\x13\n\x0b\x64\x62_response\x18\x01 \x01(\x0c\x32\x42\n\x08\x64\x61tabase\x12\x36\n\rqueryDatabase\x12\x10.databaseRequest\x1a\x11.databaseResponse\"\x00\x62\x06proto3')
)




_DATABASEREQUEST = _descriptor.Descriptor(
  name='databaseRequest',
  full_name='databaseRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='databaseRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=50,
)


_DATABASERESPONSE = _descriptor.Descriptor(
  name='databaseResponse',
  full_name='databaseResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='db_response', full_name='databaseResponse.db_response', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['databaseRequest'] = _DATABASEREQUEST
DESCRIPTOR.message_types_by_name['databaseResponse'] = _DATABASERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

databaseRequest = _reflection.GeneratedProtocolMessageType('databaseRequest', (_message.Message,), dict(
  DESCRIPTOR = _DATABASEREQUEST,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:databaseRequest)
  ))
_sym_db.RegisterMessage(databaseRequest)

databaseResponse = _reflection.GeneratedProtocolMessageType('databaseResponse', (_message.Message,), dict(
  DESCRIPTOR = _DATABASERESPONSE,
  __module__ = 'database_pb2'
  # @@protoc_insertion_point(class_scope:databaseResponse)
  ))
_sym_db.RegisterMessage(databaseResponse)



_DATABASE = _descriptor.ServiceDescriptor(
  name='database',
  full_name='database',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=93,
  serialized_end=159,
  methods=[
  _descriptor.MethodDescriptor(
    name='queryDatabase',
    full_name='database.queryDatabase',
    index=0,
    containing_service=None,
    input_type=_DATABASEREQUEST,
    output_type=_DATABASERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DATABASE)

DESCRIPTOR.services_by_name['database'] = _DATABASE

# @@protoc_insertion_point(module_scope)
